const temples = [
  {
    id: 1,
    name: "Kashi Vishwanath Temple",
    slug: "kashi-vishwanath",
    deity: "Lord Shiva",
    otherNames: ["Golden Temple of Varanasi"],
    location: {
      city: "Varanasi",
      state: "Uttar Pradesh",
      country: "India",
      coordinates: { lat: 25.3109, lng: 83.0107 },
      nearbyRiver: "Ganga",
      address: "Lahori Tola, Varanasi",
    },
    images: [
      "https://i.pinimg.com/736x/d2/51/d9/d251d9e17fb65d0fd54f9dd47a2a9ac8.jpg",
      "https://i.pinimg.com/1200x/cd/18/c4/cd18c4585728c9d865c48c45cca701a7.jpg",
      "https://i.pinimg.com/736x/40/63/e3/4063e3d3533014d1513c59dfea459463.jpg",
    ],
    historicalInfo: {
      builtIn: "Ancient (reconstructed in 1780)",
      builtBy: "Ahilyabai Holkar",
      significance: "One of the 12 Jyotirlingas",
    },
    architecture: {
      style: "Nagara",
      material: "Stone & Gold",
      notableFeatures: ["Golden dome", "Jyotirlinga"],
    },
    rituals: {
      dailyAarti: ["Mangala Aarti", "Sandhya Aarti"],
      specialPoojas: ["Rudrabhishek"],
    },
    timings: { open: "3:00 AM", close: "11:00 PM" },
    entryFee: "Free",
    bestTimeToVisit: "Oct–Mar",
    festivals: ["Mahashivratri"],
    crowdLevel: "Very High",
    nearbyAttractions: ["Dashashwamedh Ghat"],
    facilities: ["Locker", "Security"],
    howToReach: {
      byAir: "Varanasi Airport",
      byRail: "Varanasi Junction",
    },
    officialWebsite: "https://shrikashivishwanath.org",
    rating: 4.8,
  },

  {
    id: 2,
    name: "Tirupati Balaji Temple",
    slug: "tirupati-balaji",
    deity: "Lord Venkateswara",
    otherNames: ["Tirumala Temple"],
    location: {
      city: "Tirupati",
      state: "Andhra Pradesh",
      country: "India",
      coordinates: { lat: 13.6833, lng: 79.3476 },
      hill: "Tirumala Hills",
    },
    images: [
      "https://i.pinimg.com/736x/67/7d/9f/677d9fe0bb89d3ce4ff840494647959a.jpg",
      "https://i.pinimg.com/736x/f0/63/ae/f063aedc86ec1a4a943f9a8b41d2d81a.jpg",
      "https://i.pinimg.com/1200x/9a/ec/f7/9aecf781d8bfc427bc88525be2af5f92.jpg",
    ],
    historicalInfo: {
      builtIn: "300 AD (approx)",
      dynasty: "Pallava, Chola",
      significance: "Richest temple in world",
    },
    architecture: {
      style: "Dravidian",
      material: "Granite",
      notableFeatures: ["Golden roof", "Gopuram"],
    },
    rituals: {
      dailyAarti: ["Suprabhatam"],
      specialPoojas: ["Kalyanotsavam"],
      hairOffering: true,
    },
    timings: { open: "2:30 AM", close: "1:30 AM" },
    entryFee: "Free / ₹300 special darshan",
    bestTimeToVisit: "Sep–Feb",
    festivals: ["Brahmotsavam"],
    crowdLevel: "Extremely High",
    nearbyAttractions: ["Akasa Ganga"],
    facilities: ["Free food", "Stay"],
    howToReach: {
      byAir: "Tirupati Airport",
      byRail: "Tirupati Station",
    },
    officialWebsite: "https://tirumala.org",
    rating: 4.9,
  },

  {
    id: 3,
    name: "Jagannath Temple",
    slug: "jagannath-puri",
    deity: "Lord Jagannath",
    location: {
      city: "Puri",
      state: "Odisha",
      country: "India",
      coordinates: { lat: 19.8047, lng: 85.8174 },
      nearSea: "Bay of Bengal",
    },
    images: [
      "https://i.pinimg.com/1200x/d3/64/7d/d3647d1e51cea36c2a0a690dcdd10032.jpg",
      "https://i.pinimg.com/736x/5a/c7/98/5ac79851f317652e5005e91ff28ff029.jpg",
      "https://i.pinimg.com/736x/62/3e/61/623e613f018d941e97fb98a113223100.jpg",
    ],
    historicalInfo: {
      builtIn: "12th century",
      builtBy: "King Anantavarman",
      significance: "Char Dham Yatra",
    },
    architecture: {
      style: "Kalinga",
      material: "Stone",
    },
    rituals: {
      specialPoojas: ["Rath Yatra"],
    },
    timings: { open: "5:00 AM", close: "12:00 AM" },
    entryFee: "Free",
    bestTimeToVisit: "Oct–Feb",
    festivals: ["Rath Yatra"],
    restrictions: ["Only Hindus allowed"],
    nearbyAttractions: ["Konark Sun Temple"],
    facilities: ["Prasad"],
    officialWebsite: "https://jagannath.nic.in",
    rating: 4.7,
  },

  {
    id: 4,
    name: "Kedarnath Temple",
    slug: "kedarnath",
    deity: "Lord Shiva",
    location: {
      city: "Kedarnath",
      state: "Uttarakhand",
      country: "India",
      coordinates: { lat: 30.7352, lng: 79.0669 },
      altitude: "3583m",
    },
    images: [
      "https://i.pinimg.com/1200x/e5/1a/2c/e51a2c91647858284dab3c5a3875ec58.jpg",
      "https://i.pinimg.com/1200x/5c/da/2b/5cda2b99127c7afa6e1e2b6b08efd217.jpg",
    ],
    historicalInfo: {
      builtIn: "8th century",
      builtBy: "Adi Shankaracharya",
      significance: "Jyotirlinga & Char Dham",
    },
    architecture: {
      style: "Himalayan stone",
    },
    rituals: {
      dailyAarti: ["Morning & Evening"],
    },
    timings: {
      openMonths: "Apr–Nov",
      closedMonths: "Winter",
    },
    entryFee: "Free",
    trekDistance: "16 km",
    nearbyAttractions: ["Bhairavnath Temple"],
    facilities: ["Helicopter", "Medical"],
    officialWebsite: "https://badrinath-kedarnath.gov.in",
    rating: 4.9,
  },

  {
    id: 5,
    name: "Meenakshi Temple",
    slug: "meenakshi-temple",
    deity: "Goddess Meenakshi & Lord Shiva",
    location: {
      city: "Madurai",
      state: "Tamil Nadu",
      country: "India",
      coordinates: { lat: 9.9195, lng: 78.1193 },
    },
    images: [
      "https://i.pinimg.com/1200x/f4/0f/2c/f40f2c1d317c3e02409f519594cf80a3.jpg",
      "https://i.pinimg.com/1200x/c0/c2/99/c0c299dbd6758a13d3fb47589e95d7d5.jpg",
    ],
    historicalInfo: {
      builtIn: "17th century",
      dynasty: "Nayak",
      significance: "Major South Indian pilgrimage",
    },
    architecture: {
      style: "Dravidian",
      notableFeatures: ["Gopurams", "1000 pillar hall"],
    },
    rituals: {
      specialPoojas: ["Meenakshi Thirukalyanam"],
    },
    timings: { open: "5:00 AM", close: "10:00 PM" },
    entryFee: "Free",
    bestTimeToVisit: "Oct–Mar",
    festivals: ["Chithirai Festival"],
    nearbyAttractions: ["Thirumalai Palace"],
    facilities: ["Guides"],
    officialWebsite: "https://maduraimeenakshi.org",
    rating: 4.8,
  },
];

export default temples;
